### ISSUE TITLE
Add to Yeoman generators list

### ISSUE THREAD

**Issue by berkandirim** [ofkindness/generator-express-es6#13]
@ofkindness Do you want to add this generator to the list at Yeoman website?
https://yeoman.io/generators/

It would be easier for people to find. I can make the necessary changes and create a PR if you like.

**Comment by ofkindness** [comment]
It's already on this site, you can find it by `express-es6`

or did i miss something?

**Comment by berkandirim** [comment]
Oh, I haven't noticed because it doesn't come up when I search just "es6".
