### ISSUE TITLE
Add more template engines

### ISSUE THREAD

**Issue by ofkindness** [ofkindness/generator-express-es6#9]
- [x] pug
- [x] handlebars 
- [x] squirrelly 
- [x] eta
- [x] nunjucks
- [x] liquid

**Comment by berkandirim** [comment]
#12 for Handlebars

**Comment by ofkindness** [comment]
Thank you for your contribution @berkandirim, I'll proceed with your PR today

**Comment by ofkindness** [comment]
https://github.com/ofkindness/generator-express-es6/pull/29 for squirrelly

**Comment by ofkindness** [comment]
https://github.com/ofkindness/generator-express-es6/pull/30 for eta

**Comment by ofkindness** [comment]
https://github.com/ofkindness/generator-express-es6/pull/31 for nunjucks
